### ISSUE TITLE
Include bnx2 firmwares (bnx2: Can't load firmware file "bnx2/bnx2-rv2p-09-6.0.17.fw")

### ISSUE THREAD

**Issue by maximd** [FOGProject/fos#11]
Hi,

We have Dell servers using the bnx2 firmware `bnx2-rv2p-09-6.0.17.fw` and, when FOS boots and tries to initiliaze the network, the following message appears:

```
bnx2: Can't load firmware file "bnx2/bnx2-rv2p-09-6.0.17.fw"
```

As a fix, I followed https://wiki.fogproject.org/wiki/index.php/Modifying_the_Init_Image to add the bnx2 firmwares that I copied from the [firmware-bnx2 debian package](https://packages.debian.org/stretch/firmware-bnx2).

I stumbled upon https://forums.fogproject.org/topic/2156/latest-fog-0-33b/420 and https://forums.fogproject.org/topic/601/bugs-in-fog-0-33/234 where it seems that you included the firmare directly in the driver. But maybe `bnx2-rv2p-09-6.0.17.fw` is more recent and needs to be included too?

**Comment by mastacontrola** [comment]
Added to kernel firmware. You can download them at https://fogproject.org/kernels/bzImage and https://fogproject.org/kernels/bzImage32.

They should be available via the GUI as well, but will have the version label `4.17.0-addbnx`
