### ISSUE TITLE
db_root: can not open: /etc/target in FOS boot

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fos#20]
A couple of people have noticed the message `db_root: can not open: /etc/target` when booting up clients in FOS environment. Not sure when this came into play, what is causing it and if it is doing any harm. So far we don't have any reports for this being a real problem.

Still I think we should look into it and figure out where it is coming from.

**Comment by Quazz** [comment]
Looks like this is introduced between kernel 4.17.0 and 4.18.3

Some quick googling suggests this has to do with SCSI:

> scsi: target: prefer dbroot of /etc/target over /var/target

So I guess a symlink between those locations could be sufficient to squash this.

**Comment by Sebastian-Roth** [comment]
As this has been asked a couple of times in the forums now I though I might look into this.

It’s kind of strange that I still get the error even if I add that directory to the init file. I have had a look a the kernel code and can’t see why this fails. Possibly it’s because our root is not on a disk but in RAM? I am not sure. Shouldn’t make a difference really.

Then I had a closer look at which part of the kernel that is. It’s within the SCSI target driver. See more information about it here: https://lwn.net/Articles/424004/ and https://en.wikipedia.org/wiki/LIO_(SCSI_target)

I can’t imagine anyone would need this within the FOS system at all. We might just remove CONFIG_TARGET_CORE from our kernel config and that’s it. Tom and George agreed to the idea in a [forum post](https://forums.fogproject.org/topic/13024/db_root-cannot-open-etc-target).

I am in the process of building and testing. Will push a changed kernel config soon.

**Comment by Sebastian-Roth** [comment]
Fixed in 3cdb08d
