### ISSUE TITLE
rcu kernel stalls on Dell servers and possibly other platforms

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fos#31]
Follow the full discussion in the forums: https://forums.fogproject.org/topic/13742/rcu_sched-stall-or-kernel-panic-on-poweredge-r640

George suggested enabling `CONFIG_INTEL_IDLE` and `CONFIG_MAXSMP` (Enable Maximum number of SMP Processors and NUMA Nodes) in the kernel config ([reference](https://forums.fogproject.org/post/128217)).

**Comment by Quazz** [comment]
Haven't had a chance yet to check this out.

**Comment by Quazz** [comment]
@Sebastian-Roth I compiled a kernel with the aditional arguments and haven't ran into any issues since deploying it.

**Comment by Sebastian-Roth** [comment]
@Quazz Totally forgot I opened this issue as well. We'll see what the forum discussion ends up with and close this accordingly.
