### ISSUE TITLE
Update partclone to 0.3.19

### ISSUE THREAD

**Issue by Quazz** [FOGProject/fos#43]
Which would allow us to remove the CRC patch since that's now merged into source. 

There also seems to be improvements to APFS, HFS+, BTRFS and such support too.

**Comment by Sebastian-Roth** [comment]
Test build with v0.3.20 is available now: https://github.com/FOGProject/fos/releases/tag/testing

**Comment by Sebastian-Roth** [comment]
Also available with the latest official dev-branch since a few days: https://github.com/FOGProject/fos/releases/tag/20221009

**Comment by Sebastian-Roth** [comment]
The new inits have been in use for a months no without any negative reports so far. Closing as fixed. Partclone 0.3.20 will be included in the next official release.
