### ISSUE TITLE
BTRFS udev error and exFAT-FS weird messages when capturing/deploying BTRFS partitions

### ISSUE THREAD

**Issue by Piotr86PL** [FOGProject/fos#46]
Hello!

I recently installed Fedora on a BTRFS file system and wanted to make an image of it. It turned out that creating a resizable image, was throwing errors. This was caused by a typo in the script, which I have now corrected and sent a pull request. However, when capturing/deploying the image, the screen is flooded with a large number of errors like "udevd[1852]: failed to execute (...)". (as shown in the screenshot). Also, when mounting a partition as /tmp/btrfs, exFAT-FS-related errors appear, which is even stranger, because I do not have any exFAT partitions (sda3 is BTRFS). In the end, these errors do not affect the operation of the whole thing and everything works, but it just looks wrong.

The problem with udev is caused by the eudev package in Buildroot, where additional parameters should be added to the makefile (as here: https://bugs.gentoo.org/show_bug.cgi?id=739268).

As for the exFAT-FS problem, I have no idea. It mounts correctly, so why the problem. Nevertheless, it would be fitting to fix both problems.

I am using:
FOG Project: 1.5.175
Kernel: 5.17.68
Init.xz: Custom based on the latest one (added patches from pull request)
Captured system: Fedora 36 on BTRFS file system (Virtual Machine)

EXFAT-FS Error
![EXFAT_ERRORS](https://user-images.githubusercontent.com/39170443/193348286-a7dd1d27-e7c9-4211-9e46-b6d1c5cf66ae.png)

Udev Error
![UDEV_ERROR](https://user-images.githubusercontent.com/39170443/193348288-9435bb96-f5e4-401b-af25-7710faf1cd6c.png)

**Comment by Piotr86PL** [comment]
Mam dobre wieści w tej sprawie. Udało mi się rozwiązać oba problemy. 

Problem związany z eudev został już naprawiony w najnowszych wersjach Buildroot (od teraz używają tego: https://github.com/eudev-project/eudev). Użyłem więc wersji 2022.02.5 i zbudowałem nowy init.xz. Przy budowaniu nowej wersji, po prostu zgadzałem się na ustawienia proponowane przez Buildroot, jeżeli chodzi o migrację konfiguracji (zmieniłem tylko kernel headers na 5.15.X). Jeszcze poddam ten init.xz, dalszemu testowaniu, chociaż nie widzę żadnych problemów w działaniu jak na razie (działa Unicast, Multicast i Capture)

![UDEV_ERROR_GONE](https://user-images.githubusercontent.com/39170443/193417115-c4041feb-961d-4822-8d0f-0cec8ab96546.png)

Rozwiązanie tego dziwnego problemu z exFAT-FS jest jeszcze prostsze. Wystarczy w pliku funcs.sh zamienić:
mount $part /tmp/btrfs >>/tmp/btrfslog.txt 2>&1
na:
mount -t btrfs $part /tmp/btrfs >>/tmp/btrfslog.txt 2>&1

Podanie systemu plików prawdopodobnie po prostu wymusza użycia sterownika BTRFS i dzięki temu exFAT-FS nie rzuca błędami.

![EXFATERROR_GONE](https://user-images.githubusercontent.com/39170443/193417117-de04a35e-e66f-4b18-95cf-ff31980590a9.png)

Jeżeli chodzi o problem z eudev to decyzję co robić pozostawiam bardziej doświadczonym deweloperom, a co do exFAT-FS to przygotuję odpowiedniego pull request ze zmienioną komendą.

**Comment by Sebastian-Roth** [comment]
This is being worked on in the [partclone-0320 branch](https://github.com/FOGProject/fos/commits/partclone-0320).

Latest FOS inits currently use buildroot 2022.02.6: https://github.com/FOGProject/fos/releases/tag/20221009

We wait for people to test and report.

**Comment by Sebastian-Roth** [comment]
The move to buildroot 2022.02.6 has not triggered any related issue reports yet. A fair amount of people are using the latest inits on dev-branch to cover at least some basic testing. So I think we can close this one as solved.

@Piotr86PL Thanks for your work on this topic.
