### ISSUE TITLE
Probably a typo in funcs.sh

### ISSUE THREAD

**Issue by Piotr86PL** [FOGProject/fos#56]
Hello!

I'm looking through the FOS scripts for myself and it got me thinking. [Here](https://github.com/FOGProject/fos/blob/master/Buildroot/board/FOG/FOS/rootfs_overlay/usr/share/fog/lib/funcs.sh#L1997) it shouldn't be:
EBRFileName "/tmp" "$disk_number" **"$part_number"** ?

I don't know if this strongly affects the operation of FOG, but I think it's a typo.

**Comment by Sebastian-Roth** [comment]
@Piotr86PL Thanks for looking into this and pointing it out! Pretty sure you are right. Well spotted.

As hardly anyone uses extended partitions on those kind of systems no one noticed I suppose. Please send in a PR if you can. Otherwise we'll just quickly fix it.
