### ISSUE TITLE
Add storage space check for image captures.

### ISSUE THREAD

**Issue by rluzuriaga** [FOGProject/fos#60]
Currently, when capturing an image and the storage node disk is full, the output message is not very descriptive.
Current output message: `Failed to create image capture path (prepareUploadLocation)`

There was this [forum post](https://forums.fogproject.org/topic/16683/failed-to-create-image-capture-path-fog-project) that made me think that maybe there should be a check if the storage node disk is full and display a more descriptive message.

What do you think @Sebastian-Roth?
I could start work on this later in the week.

**Comment by Sebastian-Roth** [comment]
Definitely a good idea! Will be interesting to see how you can get that information from the server to the client machine.
