### ISSUE TITLE
Change fog.wipe to wipe NVMe drives correctly.

### ISSUE THREAD

**Issue by rluzuriaga** [FOGProject/fos#61]
The `fog.wipe` script currently uses `shred` or `dd` to wipe out the hard drive.
Wiping an SSD or NVMe drive like this will make the drives deteriorate very quickly.

**Comment by Sebastian-Roth** [comment]
@rluzuriaga I though we had that fixed already in #40

**Comment by rluzuriaga** [comment]
@Sebastian-Roth I did some more research and yes everything said in #40 is correct. SSDs are frozen at boot from the UEFI, the way to unfreeze them would be to suspend the computer. Suspending the computer of course does not work on FOS since it is a login shell. SSDs will have to keep using `shred` and `dd`.

An NVMe is a different story. UEFI does not freeze an NVMe. NVMe drives have their own way to format using `nvme-cli`. I will work on implementing this.
