### ISSUE TITLE
Buildscript failing on package dependency on Debian

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fos#62]
Just figured we have an issue in the script:
```
./build.sh -k -a x64
Checking packages needed for building
 * Package libelf-dev missing!
Package(s) missing, can't build, exiting now.
```
When manually running the package command I see this:
```
dpkg -s libelf-dev
dpkg-query: error: --status needs a valid package name but 'libelf-dev' is not: ambiguous package name 'libelf-dev' with more than one installed instance
```
Maybe we can switch to using `dkpg -l | grep -q "packagename"`?

**Comment by Sebastian-Roth** [comment]
@JlnWntr Was gonna as if you might want to look into this. Though I was in kind of a need and quickly fixed this in commit 1c7ffee (still untested on RedHat based systems).

What do you think? Any better way of doing this?

**Comment by rluzuriaga** [comment]
@Sebastian-Roth I just tested the changes on Ubuntu and Fedora, there was no issues with the changes

**Comment by Sebastian-Roth** [comment]
@rluzuriaga Good point you got there. While it's a bit hackish what about `rpm -qa | grep -q "packagename-"`? Should be working for pretty much all packages on Debian/Ubuntu/RedHat I think.

**Comment by rluzuriaga** [comment]
@Sebastian-Roth Even though it is a bit hackish, it seems to work better. With the added dash after the package name, `flex` is now being seen in Fedora.
Ubuntu by default does not show the missing packages, but PR #58 fixes that issue. On Ubuntu Server (minimized) there are some packages like rsync that are not installed. The `packagename-` catches that rsync as missing, while without the dash it does not catch it.

**Comment by Sebastian-Roth** [comment]
@rluzuriaga I am going to close this issue for now. If we run into more package issues we'll just revise this topic here.
