### ISSUE TITLE
e2fsck has unsupported feature(s): FEATURE_C12

### ISSUE THREAD

**Issue by ikarus23** [FOGProject/fos#79]
Hi! Sorry, I'm not sure if I'm at the right pace.

I set up an Archlinux image using ext4 which I wanted to manage with fog. However, the tool for "collecting" or rolling out the image (small Linux environment booed via PXE, fog-client?!) stops with an error:
```
e2fsck has unsupported feature(s): FEATURE_C12
```
It seams the ext4 used by Arch has a "modern" filesystem flag, which the version of e2fsck from the PXE image has no support yet.

Is there an easy way to fix this? Do I have to build a "modern" PXE image myself? Thanks for any hints.

**Comment by rluzuriaga** [comment]
@ikarus23 The version of e2fsck in our inits is a bit outdated. Can you try replacing your init with the one in [this release](https://github.com/rluzuriaga/fos/releases/tag/20231124) and let me know if you still have the same issue.

**Comment by ikarus23** [comment]
Hi. Thanks for the detailed instructions. I will try that. Please be patient (It might take some time until I will have the opportunity to test it).

**Comment by lookmomnohands** [comment]
I'm really glad y'all have both the detail reasoning and instructions, I have moved my home lab up to the above mentioned devel kernel, moved both I it's per the instructions, even rebuilt fog, and still I get this C12 for Manjaro. I'm a total noob to PXE boots, but shouldn't the error have changed? I'm missing something.

**Comment by ikarus23** [comment]
Thanks for testing. For me it will still be some more time before I can test. But your findings already seem to confirm: the version is still too old.

**Comment by rluzuriaga** [comment]
@ikarus23 I just release the newest kernels/inits https://github.com/FOGProject/fos/releases/tag/EXP_20240430
These inits have the newest version of e2fsprogs which should resolve this issue.

Can you try it out and let us know of any issues?

**Comment by rluzuriaga** [comment]
This has been fixed and tested as of commit https://github.com/FOGProject/fos/commit/dc9656b08f369f9746372020456158d95cd2e0fa
