### ISSUE TITLE
Sapphire Rapids CPU won't boot using 6.6.34 bzImage

### ISSUE THREAD

**Issue by mmarcini** [FOGProject/fos#88]
A Sapphire Rapids CPU won't efi boot using the 6.6.34 kernel.

The BIOS is:

BIOS Information
        Vendor: Intel Corporation
        Version: SE5C741.86B.01.02.0001.2401260138

The issue also exists with a follow-on CPU.

An initial workaround was to disable Virtualization in BIOS:

under Processor

Virtualization 

X2APIC

under IO

VT-D

 

For Future SKUs with a larger core count may need to be dropped to 56 cores in the BIOS as well.

**Comment by mmarcini** [comment]
The same kernel build with the attached config file boots fine on a RHEL 9.3 server.

[config-6.6.34.txt](https://github.com/user-attachments/files/16057608/config-6.6.34.txt)

**Comment by mastacontrola** [comment]
I'm not sure what problem you're trying to solf.

These kernels aren't for booting on RHEL 9.3 at all, but rather for FOGs initrd system.

**Comment by mmarcini** [comment]
> I'm not sure what problem you're trying to solve.
> 
> These kernels aren't for booting on RHEL 9.3 at all, but rather for FOGs initrd system.

I wanted to prove that the hardware "could" boot.   I generated a 6/6/34 kernel based on a non-FOS config just to confirm that.

I have a config file patch that adds some specific intel IOMMU settings that I will present in a pull request shortly, just doing some final debug.   I looked at the config file differences between kernelx64.config and the attached config to generate missing config settings.

**Comment by mmarcini** [comment]
BTW, I noticed the master branch kernel-headers generation and the bzImage kernel are out of sync with their respective versions.

Is that intentional?

**Comment by mastacontrola** [comment]
So, though, init's show up as having 6.1.62 where the kernel's configs directly are using 6.6.34. The init generation has the ability to build kernels as part of the FS, though genernally we don't worry too much about this. I believe there are parts where we needed to build the kernel alongside for things that must be modular by design of FS->kernel interactions. Where we cannot build the piece directly into the kernel.

That said I think it's nothing to worry about at this point. That can be fixed or adjusted as necessary later on.

Looking at what I could of your config provided, I'm seeing you have set a lot of the items to modules. While this can work, since the idea of these kernels are to provide all the necessarily things internalized, modules aren't really something we've dug into since we have to build the kernels independent of the initrd. Is there any way you could limit the changes to the config to those required to make them build and operate?

Here's the changes I see currently:
[configdiffs.diff.txt](https://github.com/user-attachments/files/16066002/configdiffs.diff.txt)

**Comment by mastacontrola** [comment]
I will work on seeing if I can get the headers up to date with th 6.6.34 version.

**Comment by mastacontrola** [comment]
I'm updated the build script to use 2024.5 version of buildroot and updated the fs configs to update binutils, gcc versions along with the headers being updated for 6.6 (which buildroot uses 6.6.32 right now)

This is currently building a release right now.

**Comment by mmarcini** [comment]
> Looking at what I could of your config provided, I'm seeing you have set a lot of the items to modules. While this can work, since the idea of these kernels are to provide all the necessarily things internalized, modules aren't really something we've dug into since we have to build the kernels independent of the initrd. Is there any way you could limit the changes to the config to those required to make them build and operate?
> 
I'm in the process of doing that now!

**Comment by mmarcini** [comment]
[kernelx64.config.txt](https://github.com/user-attachments/files/16073203/kernelx64.config.txt)

Here is a FOS config file that boots.   I have this in a fork ready to go.

**Comment by mmarcini** [comment]
> [kernelx64.config.txt](https://github.com/user-attachments/files/16073203/kernelx64.config.txt)
> 
> Here is a FOS config file that boots. I have this in a fork ready to go. Just strip off the .txt suffix.
> 
> It is relative to the 6.6.34 kernel.

I was delayed because the BMC KVM stopped working.  The SOL did work, but I'm guessing the kernel command line needs serial console stuff that usb grub didn't have.   ipmitool mc reset cold brought the KVM back.

**Comment by jmalanto** [comment]
I just wanted to add that the issue we were seeing was the same as https://forums.fogproject.org/topic/16993/client-hangs-at-efi-stub
The change resolves the issue without disabling VT and X2APIC in the BIOS

**Comment by mmarcini** [comment]
> I just wanted to add that the issue we were seeing was the same as https://forums.fogproject.org/topic/16993/client-hangs-at-efi-stub The change resolves the issue without disabling VT and X2APIC in the BIOS

I don't see a change other than the BIOS detours, which we know about.   Did I miss something in my quick pass through?

We need the BIOS settings in place for post image use.

I suspect the config changes could be condensed a bit.

**Comment by mastacontrola** [comment]
Sorry for the typo on the name, but I have pushed this into the branch and am buidling an expermental as we speak.

Thank you @mmarcini

**Comment by mmarcini** [comment]
> Sorry for the typo on the name, but I have pushed this into the branch and am buidling an expermental as we speak.
> 
> Thank you @mmarcini

I suspect the changes could be paired down a bit.   If you want to suggest any changes, I can keep the server and ubuntu build environment for a bit longer.

**Comment by mmarcini** [comment]
> > Sorry for the typo on the name, but I have pushed this into the branch and am buidling an expermental as we speak.
> > Thank you @mmarcini
> 
> I suspect the changes could be paired down a bit. If you want to suggest any changes, I can keep the server and ubuntu build environment for a bit longer.

The new bzImage/init.xz from https://github.com/FOGProject/fos/releases/tag/EXP_20240705 works!

**Comment by mmarcini** [comment]
The there is an experimental build with my config:  https://github.com/FOGProject/fos/releases/tag/EXP_20240705.

It works from the USB stack.  John, can you test the bzImage/init.xz from here?

**Comment by mmarcini** [comment]
We have tested https://github.com/FOGProject/fos/releases/tag/EXP_20240705 now both on a USB stick and for a FOG deployment and it works!

I'm resolving this issue!
